# Generated by Django 3.2 on 2021-04-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(default='', upload_to='gallery/')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
